In [1]:
# Import required libraries
# Pandas is used for data manipulation
# SQLite3 is used to create and connect to the database

import pandas as pd
import sqlite3

In [2]:
# Load the CSV dataset into a Pandas DataFrame
# Replace the file path with your dataset location

df = pd.read_csv(r"C:\Users\somes\OneDrive\Pictures\Attachments\Desktop\Documents\apex planet\task-2\SuperMarket Analysis.csv")

# Display the first five rows
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3

In [3]:
# Display dataset information
# Shows number of rows, columns, data types and missing values

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               1000 non-null   str
 1   Branch                   1000 non-null   str
 2   City                     1000 non-null   str
 3   Customer type            1000 non-null   str
 4   Gender                   1000 non-null   str
 5   Product line             1000 non-null   str
 6   Unit price               1000 non-null   float64
 7   Quantity                 1000 non-null   int64
 8   Tax 5%                   1000 non-null   float64
 9   Sales                    1000 non-null   float64
 10  Date                     1000 non-null   str
 11  Time                     1000 non-null   str
 12  Payment                  1000 non-null   str
 13  cogs                     1000 non-null   float64
 14  gross margin percentage  1000 non-null   float64
 15  gross income             1000 non-null   float64
 16  Rating                   1000 non-null   float64
dtypes: float64(7), int64(1), str(9)
memory usage: 132.9 KB

In [4]:
# Display all column names
# Helps while writing SQL queries

print(df.columns.tolist())

['Invoice ID', 'Branch', 'City', 'Customer type', 'Gender', 'Product line', 'Unit price', 'Quantity', 'Tax 5%', 'Sales', 'Date', 'Time', 'Payment', 'cogs', 'gross margin percentage', 'gross income', 'Rating']

In [5]:
# Create (or connect to) SQLite database
# A new database file named supermarket.db will be created

conn = sqlite3.connect("supermarket.db")

print("Database Connected Successfully")

Database Connected Successfully

In [6]:
# Store the DataFrame into SQLite
# Creates a table named 'sales'

df.to_sql("sales", conn, if_exists="replace", index=False)

print("Table Created Successfully")

Table Created Successfully

In [7]:
# Display first 10 rows from the sales table

query = """
SELECT *
FROM sales
LIMIT 10;
"""

pd.read_sql(query, conn)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3
5,699-14-3026,Giza,Naypyitaw,Member,Female,Electronic accessories,85.39,7,29.8865,627.6165,3/25/2019,6:30:00 PM,Ewallet,597.73,4.761905,29.8865,4.1
6,355-53-5943,Alex,Yangon,Member,Female,Electronic accessories,68.84,6,20.6520,433.6920,2/25/2019,2:36:00 PM,Ewallet,413.04,4.761905,20.6520,5.8
7,315-22-5665,Giza,Naypyitaw,Member,Female,Home and lifestyle,73.56,10,36.7800,772.3800,2/24/2019,11:38:00 AM,Ewallet,735.60,4.761905,36.7800,8.0
8,665-32-9167,Alex,Yangon,Member,Female,Health and beauty,36.26,2,3.6260,76.1460,1/10/2019,5:15:00 PM,Credit card,72.52,4.761905,3.6260,7.2
9,692-92-5582,Cairo,Mandalay,Member,Female,Food and beverages,54.84,3,8.2260,172.7460,2/20/2019,1:27:00 PM,Credit card,164.52,4.761905,8.2260,5.9

In [8]:
# Calculate total sales

query = """
SELECT SUM(Sales) AS Total_Sales
FROM sales;
"""

pd.read_sql(query, conn)

   Total_Sales
0   322966.749

In [9]:
# Calculate average sales

query = """
SELECT AVG(Sales) AS Average_Sales
FROM sales;
"""

pd.read_sql(query, conn)

   Average_Sales
0     322.966749

In [10]:
# Display top 10 highest sales transactions

query = """
SELECT *
FROM sales
ORDER BY Sales DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,860-79-0874,Giza,Naypyitaw,Member,Female,Fashion accessories,99.30,10,49.650,1042.650,2/15/2019,2:53:00 PM,Credit card,993.0,4.761905,49.650,6.6
1,687-47-8271,Alex,Yangon,Normal,Male,Fashion accessories,98.98,10,49.490,1039.290,2/8/2019,4:20:00 PM,Credit card,989.8,4.761905,49.490,8.7
2,283-26-5248,Giza,Naypyitaw,Member,Female,Food and beverages,98.52,10,49.260,1034.460,1/30/2019,8:23:00 PM,Ewallet,985.2,4.761905,49.260,4.5
3,751-41-9720,Giza,Naypyitaw,Normal,Male,Home and lifestyle,97.50,10,48.750,1023.750,1/12/2019,4:18:00 PM,Ewallet,975.0,4.761905,48.750,8.0
4,303-96-2227,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.690,1022.490,3/2/2019,5:16:00 PM,Ewallet,973.8,4.761905,48.690,4.4
5,744-16-7898,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.37,10,48.685,1022.385,1/15/2019,1:48:00 PM,Credit card,973.7,4.761905,48.685,4.9
6,271-88-8734,Giza,Naypyitaw,Member,Female,Fashion accessories,97.21,10,48.605,1020.705,2/8/2019,1:00:00 PM,Credit card,972.1,4.761905,48.605,8.7
7,234-65-2137,Giza,Naypyitaw,Normal,Male,Home and lifestyle,95.58,10,47.790,1003.590,1/16/2019,1:32:00 PM,Cash,955.8,4.761905,47.790,4.8
8,554-42-2417,Giza,Naypyitaw,Normal,Female,Sports and travel,95.44,10,47.720,1002.120,1/9/2019,1:45:00 PM,Cash,954.4,4.761905,47.720,5.2
9,325-77-6186,Alex,Yangon,Member,Female,Home and lifestyle,90.65,10,45.325,951.825,3/8/2019,10:53:00 AM,Ewallet,906.5,4.761905,45.325,7.3

In [11]:
# Calculate total sales for each city

query = """
SELECT City,
SUM(Sales) AS TotalSales
FROM sales
GROUP BY City;
"""

pd.read_sql(query, conn)

        City   TotalSales
0   Mandalay  106197.6720
1  Naypyitaw  110568.7065
2     Yangon  106200.3705

In [12]:
# Count customers based on gender

query = """
SELECT Gender,
COUNT(*) AS Customers
FROM sales
GROUP BY Gender;
"""

pd.read_sql(query, conn)

   Gender  Customers
0  Female        571
1    Male        429

In [13]:
# Calculate total sales for each product line

query = """
SELECT [Product line],
SUM(Sales) AS TotalSales
FROM sales
GROUP BY [Product line]
ORDER BY TotalSales DESC;
"""

pd.read_sql(query, conn)

             Product line  TotalSales
0      Food and beverages  56144.8440
1       Sports and travel  55122.8265
2  Electronic accessories  54337.5315
3     Fashion accessories  54305.8950
4      Home and lifestyle  53861.9130
5       Health and beauty  49193.7390

In [14]:
# Count the number of transactions for each payment method

query = """
SELECT Payment,
COUNT(*) AS TotalTransactions
FROM sales
GROUP BY Payment;
"""

pd.read_sql(query, conn)

       Payment  TotalTransactions
0         Cash                344
1  Credit card                311
2      Ewallet                345

In [15]:
# Calculate monthly sales

query = """
SELECT substr(Date,1,7) AS Month,
SUM(Sales) AS MonthlySales
FROM sales
GROUP BY Month;
"""

pd.read_sql(query, conn)

      Month  MonthlySales
0   1/1/201     4745.1810
1   1/10/20     3560.9490
2   1/11/20     2114.9625
3   1/12/20     5184.7635
4   1/13/20     2451.2040
..      ...           ...
84  3/5/201     6230.8785
85  3/6/201     3092.5965
86  3/7/201     1438.2585
87  3/8/201     3125.3880
88  3/9/201     7474.0470

[89 rows x 2 columns]

In [16]:
# Calculate total sales based on customer type

query = """
SELECT [Customer type],
SUM(Sales) AS TotalSpent
FROM sales
GROUP BY [Customer type]
ORDER BY TotalSpent DESC;
"""

pd.read_sql(query, conn)

  Customer type  TotalSpent
0        Member  189694.764
1        Normal  133271.985

In [17]:
# Calculate average customer rating for each city

query = """
SELECT City,
AVG(Rating) AS AverageRating
FROM sales
GROUP BY City;
"""

pd.read_sql(query, conn)

        City  AverageRating
0   Mandalay       6.818072
1  Naypyitaw       7.072866
2     Yangon       7.027059

In [18]:
# Find the highest sale amount

query = """
SELECT MAX(Sales) AS HighestSale
FROM sales;
"""

pd.read_sql(query, conn)

   HighestSale
0      1042.65

In [19]:
# Find the lowest sale amount

query = """
SELECT MIN(Sales) AS LowestSale
FROM sales;
"""

pd.read_sql(query, conn)

   LowestSale
0     10.6785

In [20]:
# Count transactions in each branch

query = """
SELECT Branch,
COUNT(*) AS TotalTransactions
FROM sales
GROUP BY Branch;
"""

pd.read_sql(query, conn)

  Branch  TotalTransactions
0   Alex                340
1  Cairo                332
2   Giza                328

In [21]:
# Close the SQLite database connection

conn.close()

print("Database Connection Closed Successfully")

Database Connection Closed Successfully